{% set name = "autoRIFT" %}
{% set version = "1.5.0" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nasa-jpl/autoRIFT/archive/v{{ version }}.tar.gz
  sha256: fd5afb84081e907838257a294e1028419bae30e96c8c859b881a182811281b3d



build:
  number: 5
  script: {{ PYTHON }} -m pip install --global-option=build_ext --global-option="-I${PREFIX}/include/opencv4" . -vv
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - opencv >=4.6.0                         # [build_platform != target_platform]
    - libgdal                                # [build_platform != target_platform]

  host:
    - python
    - pip
    - opencv >=4.6.0
    - libgdal
  run:
    - python
    - {{ pin_compatible('opencv', max_pin='x.x') }}
    - scipy
    - scikit-image
    - gdal
    - libgdal

test:
  imports:
    - autoRIFT
    - autoRIFT.autoRIFT
    - autoRIFT.autoriftcore
    - geogrid
    - geogrid.GeogridOptical
    - geogrid.geogridOptical

about:
  home: https://github.com/nasa-jpl/autoRIFT
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Fast pixel displacement estimation from remote sensing imagery
  doc_url: https://github.com/nasa-jpl/autoRIFT
  dev_url: https://github.com/nasa-jpl/autoRIFT

extra:
  recipe-maintainers:
    - jhkennedy
    - leiyangleon
    - piyushrpt
    - alex-s-gardner
