{% set name = "autoRIFT" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nasa-jpl/autoRIFT/archive/v{{ version }}.tar.gz
  sha256: 79e6be8d50b1e9e5bd36efaf2653fcc635287cf8eeb36ac7ce0b96061c985004

build:
  number: 0
  script: {{ PYTHON }} -m pip install --global-option=build_ext --global-option="-I${PREFIX}/include/opencv4" . -vv
  skip: true  # [win or py<310]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libgdal >=3                            # [build_platform != target_platform]
    - numpy >=1.20                           # [build_platform != target_platform]
    - opencv >=4.6.0                         # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]

  host:
    - python
    - pip
    - setuptools
    - eigen >=3.3
    - isce3 >=0.14
    - libgdal >=3
    - netCDF4
    - numpy >=1.20
    - opencv >=4.6.0                         # [build_platform == target_platform]

  run:
    - python
    - gdal >=3
    - isce3 >=0.14
    - libgdal
    - netCDF4
    - numpy >=1.20
    - numba
    - {{ pin_compatible('opencv', max_pin='x.x') }}
    - pandas >=1.4
    - s1reader >=0.2.2
    - scikit-image
    - scipy

test:
  imports:
    - autoRIFT
    - autoRIFT.autoRIFT
    - autoRIFT.autoriftcore
    - geogrid
    - geogrid.GeogridOptical
    - geogrid.geogridOptical

about:
  home: https://github.com/nasa-jpl/autoRIFT
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Fast pixel displacement estimation from remote sensing imagery
  doc_url: https://github.com/nasa-jpl/autoRIFT
  dev_url: https://github.com/nasa-jpl/autoRIFT

extra:
  recipe-maintainers:
    - jhkennedy
    - leiyangleon
    - piyushrpt
    - alex-s-gardner
