{% set name = "autoRIFT" %}
{% set version = "1.3.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leiyangleon/autoRIFT/archive/v{{ version }}.tar.gz
  sha256: 0ee119614d3afebd550b4d232e85c3ea5b3c8aeb9e9e1084419cb9aaea859015



build:
  number: 0
  script: {{ PYTHON }} -m pip install --global-option=build_ext --global-option="-I${PREFIX}/include/opencv4" . -vv
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - opencv
    - libgdal
  run:
    - python
    - {{ pin_compatible('opencv') }}
    - scipy
    - scikit-image
    - gdal
    - libgdal

test:
  imports:
    - autoRIFT
    - autoRIFT.autoRIFT
    - autoRIFT.autoriftcore
    - geogrid
    - geogrid.GeogridOptical
    - geogrid.geogridOptical

about:
  home: https://github.com/leiyangleon/autoRIFT
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Fast pixel displacement estimation from remote sensing imagery
  doc_url: https://github.com/leiyangleon/autoRIFT
  dev_url: https://github.com/leiyangleon/autoRIFT

extra:
  recipe-maintainers:
    - leiyangleon
    - piyushrpt
    - alex-s-gardner
