{% set name = "autoRIFT" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leiyangleon/autoRIFT/archive/v{{ version }}.tar.gz
  sha256: 01e294df9f5c4329d7536538dfa2da4e7aff04723d213ba2c8cf909a482740a2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - libopencv 3.4
    - opencv 3.4
  run:
    - python
    - opencv 3.4
    - libopencv 3.4
    - scipy
    - scikit-image
    - gdal

test:
  imports:
    - autoRIFT
    - autoRIFT.autoRIFT
    - autoRIFT.autoriftcore
    - geogrid.GeogridOptical

about:
  home: https://github.com/leiyangleon/autoRIFT
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Fast pixel displacement estimation from remote sensing imagery'
  doc_url: https://github.com/leiyangleon/autoRIFT
  dev_url: https://github.com/leiyangleon/autoRIFT

extra:
  recipe-maintainers:
    - leiyangleon
    - piyushrpt
