travis:
  secure:
    BINSTAR_TOKEN: kkzxb4YCRrvJwTH+bYFZ6cc/4MiXgmObv6DzW61bCiaeQksZrCkF5AmJWMCg/dn6MZ/QRB3Gan/3amKTP6ZIM6qXg0aa/KGfnCKWmsKL80ERVsrccypv9HOQOEh4isSqK6SjVlSYAL4aODicqSQ/GRl8lgdnVBzLRO3iYHTqJ4jp9qDTdumyohk/hgkKdLTzzAttNsGyo2yIT5VRaD4QvsjyNCQHO+9NOsaN2zc3RXNddEwEESXn12URLpFb++Fdjiqtdo4pqUBEzqgxlfnybzV6b5hW7FJ2884ctUllaLt/P8bGaMlv7lwVXCZw59bcD18vVZ4bTl6mK/PlfWkPmH9yEdkm8PGV1PgDp1EOgyGlKJfr4vwj9+xQFoILKpfQY+ExEbuhFYAitJb+rs5wFQJdRB6cfCIhdDzk76dLMvR1V4P4eE8mfdyIMqkcaFsI/EJk7AmyTVMTkF36uVpHBUbwjdI2tHaYV0SJeFRmKFmxV2+CHeTiki/HT8oC7FMoqa1Wj9irgKiy+ZkQLqDW1UmdI/uwC9eWgWMAB7Aqym5Gg7rbnxoW8YUSPvfr0xOLdAy0c6X/BVbKNRGOftilU23OCD7xzmy/CFB6/SpU7tiQWh83xmen0nIeq/9FbxxW9jZiTl20tyMQl+hBGDgLI3hQ/C76fy8VUm8OmObPT5I=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
